name: flutter_playground
description: "Flutter Playground"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.3.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.8
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3


flutter:
  # 이미지를 프로젝트에 포함하기 위해선 보통 assets 디렉터리 하위에 이미지 파일을 저장합니다.
  # 이미지를 저장한다고 바로 불러올 수는 없습니다. 아래에 assets 값에 이미지를 불러올 디렉터리를 지정해주어야 합니다.
  # 지정을 한 이후에는, `flutter pub get` 명령어를 통해 최신화를 수행해주어야 합니다.
  uses-material-design: true

  # 이미지를 불러오도록 허용할 프로젝트 하위의 폴더, 혹은 파일명을 추가합니다.
  assets:
    - assets/splash-screen/